cruz_todo:
    resource: "@TodoBundle/Resources/config/routing.php"
    prefix:   /
    resource: "@TodoBundle/Controller/DefaultController.php"
    type: annotation

cruz_api:
    resource: "@TodoBundle/Resources/config/routing.php"
    prefix:   /api
    resource: "@TodoBundle/Controller/ApiController.php"
    type: annotation